name: gan_game

services:
  gan_game:
    restart: unless-stopped
    image: logus2k/gan_game:latest
    container_name: gan_game
    hostname: gan_game
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [ gpu ]
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8993:8993"
    networks:
      - gan_game_network

networks:
  gan_game_network:
    external: true
    name: gan_game_network
