services:
  femulator:
    restart: unless-stopped
    image: logus2k/gan_game:latest
    container_name: gan_game
    hostname: gan_game
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5868:5868"
    networks:
      - gan_network

networks:
  femulator_network:
    external: true
    name: gan_network
